---
- hosts: localhost
  connection: local
  vars:
    aws_access_key: aws_access_key
    instance_id: aws_access_key
    aws_secret_key: aws_secret_key

  # Note: These examples do not set authentication details, see the AWS Guide for details.

- name: gather facts about an AMI using ami-id
  ec2_instance_facts: