- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:

   - name: Grab a user record
     snow_record:
         username: admin
         password: P@ssw0rd
         instance: snowsolutionsandbox
         state: present
         number: 62826bf03710200044e0bfc8bcbe5df1
         table: sys_user
         lookup_field: sys_id

 
