# basic provisioning example vpc network
- name: basic provisioning example
  hosts: localhost
  vars:
    alicloud_access_key: LTAIjkotmZULSljk
    alicloud_secret_key: 1boy3KyUzZoaBqhWmtGj06g7qDLaHK
    alicloud_region:    ap-south-1

  tasks:
    - name: launch ECS instance in VPC network
      ali_image_facts:
        alicloud_access_key: '{{ alicloud_access_key }}'
        alicloud_secret_key: '{{ alicloud_secret_key }}'
        alicloud_region: '{{ alicloud_region }}'
