# alicloud_setup.yml
- name: Create instance(s)
  hosts: localhost
  connection: local

  tasks:
   - name: Create a set of instances
     alicloud_instance:
         group_id: '{{ created_group.group_id }}'
         instance_type: ecs.n4.small
         image_id: "{{ ami_id }}"
         instance_name: "My-new-instance"
         instance_tags:
             Name: NewECS
             Version: 0.0.1
         count: 5
         count_tag:
             Name: NewECS
         allocate_public_ip: true
         max_bandwidth_out: 50
         vswitch_id: '{{ created_vsw.vswitch_id}}'